builders:
  colors:
    import: 'package:design_system_generator/builder.dart'
    builder_factories: ['colorBuilder']
    build_extensions: { '.ds.json': ['.colors.dart'] }
    auto_apply: root_package
    build_to: source

  spatials:
    import: 'package:design_system_generator/builder.dart'
    builder_factories: ['spatialBuilder']
    build_extensions: { '.ds.json': ['.spatials.dart'] }
    auto_apply: root_package
    build_to: source

  radius:
    import: 'package:design_system_generator/builder.dart'
    builder_factories: ['radiusBuilder']
    build_extensions: { '.ds.json': ['.radii.dart'] }
    auto_apply: root_package
    build_to: source

  typography:
    import: 'package:design_system_generator/builder.dart'
    builder_factories: ['typographyBuilder']
    build_extensions: { '.ds.json': ['.typography.dart'] }
    auto_apply: root_package
    build_to: source

  screens:
    import: 'package:design_system_generator/builder.dart'
    builder_factories: ['screenBuilder']
    build_extensions: { '.ds.json': ['.screens.dart'] }
    auto_apply: root_package
    build_to: source
