name: design_system_generator
description: A starting point for Dart libraries or applications.
version: 0.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build: ^2.3.1

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_test:
  lints:
