name: design_system_generator
description: |
  A generator for design system tokens, build from a json configuration for dart/flutter.
  Generates colors, spatials, breakpoints, and other useful elements from a configuration.

issue_tracker: https://github.com/smartive/flutter-design-system-generator/issues
homepage: https://github.com/smartive/flutter-design-system-generator
repository: https://github.com/smartive/flutter-design-system-generator.git

version: 5.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^3.0.0
  code_builder: ^4.10.1
  dart_style: ^3.0.1

dev_dependencies:
  build_test: ^2.2.3
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
