name: design_system_generator
description: |
  A generator for design system tokens, build from a json configuration for dart/flutter.
  Generates colors, spatials, breakpoints, and other useful elements from a configuration.

issue_tracker: https://github.com/smartive/flutter-design-system-generator/issues
homepage: https://github.com/smartive/flutter-design-system-generator
repository: https://github.com/smartive/flutter-design-system-generator.git

version: 3.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args:
  path:
  glob:

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_test:
  lints:
