name: design_system_generator
description: A starting point for Dart libraries or applications.
version: 0.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build: ^2.3.1

dev_dependencies:
  build_test: ^2.1.6
  lints: ^2.0.0
  test: ^1.21.0
