name: design_system_generator
description: |
  A generator for design system tokens, build from a json configuration for dart/flutter.
  Generates colors, spatials, breakpoints, and other useful elements from a configuration.

issue_tracker: https://github.com/smartive/flutter-design-system-generator/issues
homepage: https://github.com/smartive/flutter-design-system-generator
repository: https://github.com/smartive/flutter-design-system-generator.git

version: 5.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  build: ^4.0.0
  code_builder: ^4.11.0
  dart_style: ^3.1.1

dev_dependencies:
  build_test: ^3.4.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.2
