name: Test Package

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter analyze
      - run: dart test test_dart
      - run: flutter test
